# Generated by Django 2.0.6 on 2018-07-04 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=15)),
                ('holiday', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bank Holidays',
            },
        ),
        migrations.CreateModel(
            name='JourneyLogs',
            fields=[
                ('routeid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('segments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('seg_num', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
            ],
            options={
                'verbose_name_plural': 'Journey Logs',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('lineid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('routes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
            options={
                'verbose_name_plural': 'Lines',
            },
        ),
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.TextField(null=True)),
                ('linked', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None)),
            ],
            options={
                'verbose_name_plural': 'Linked Stops',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routeid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direction', models.IntegerField(null=True)),
                ('stopids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
            ],
            options={
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stopid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=10)),
                ('routes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('operator', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Stops',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=5, null=True)),
                ('irain', models.IntegerField(null=True)),
                ('rain', models.CharField(max_length=10, null=True)),
                ('itemp', models.IntegerField(null=True)),
                ('temp', models.CharField(max_length=10, null=True)),
                ('iwetb', models.IntegerField(null=True)),
                ('wetb', models.CharField(max_length=10, null=True)),
                ('dewpt', models.CharField(max_length=10, null=True)),
                ('vappr', models.CharField(max_length=10, null=True)),
                ('rhum', models.CharField(max_length=10, null=True)),
                ('msl', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Weather',
            },
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['rain'], name='main_weathe_rain_f14ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['date'], name='main_weathe_date_ab6e08_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['time'], name='main_weathe_time_8c35c1_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['date', 'time'], name='main_weathe_date_965487_idx'),
        ),
        migrations.AddIndex(
            model_name='stops',
            index=models.Index(fields=['stopid'], name='main_stops_stopid_486924_idx'),
        ),
        migrations.AddIndex(
            model_name='routes',
            index=models.Index(fields=['routeid'], name='main_routes_routeid_5b8362_idx'),
        ),
        migrations.AddIndex(
            model_name='linked',
            index=models.Index(fields=['stop_name'], name='main_linked_stop_na_3f3cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='linked',
            index=models.Index(fields=['linked'], name='main_linked_linked_6d05c0_idx'),
        ),
        migrations.AddIndex(
            model_name='lines',
            index=models.Index(fields=['lineid'], name='main_lines_lineid_dad144_idx'),
        ),
        migrations.AddIndex(
            model_name='journeylogs',
            index=models.Index(fields=['routeid'], name='main_journe_routeid_4a6a75_idx'),
        ),
    ]
