# Generated by Django 2.0.7 on 2018-07-02 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.TextField(null=True)),
                ('linked', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None)),
            ],
            options={
                'verbose_name_plural': 'Linked Stops',
            },
        ),
        migrations.AddIndex(
            model_name='linked',
            index=models.Index(fields=['stop_name'], name='main_linked_stop_na_3f3cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='linked',
            index=models.Index(fields=['linked'], name='main_linked_linked_6d05c0_idx'),
        ),
    ]
