# Generated by Django 2.0.6 on 2018-06-15 15:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBusStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopid', models.CharField(max_length=200)),
                ('loadtime', models.CharField(max_length=200)),
                ('busstopname', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lud', models.CharField(max_length=200)),
                ('routes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('flag', models.CharField(max_length=200)),
            ],
        ),
    ]
