# Generated by Django 2.0.6 on 2018-08-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fares',
        ),
    ]
