# Generated by Django 2.0.6 on 2018-08-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_fares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField(null=True)),
                ('route', models.CharField(max_length=10)),
                ('direction', models.IntegerField(null=True)),
                ('stage', models.IntegerField(null=True)),
                ('pattern_id', models.CharField(max_length=10)),
                ('seq', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Fares',
            },
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['stop'], name='main_fares_stop_e66422_idx'),
        ),
    ]
