# Generated by Django 2.0.6 on 2018-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dublinweather_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dublinweather',
            index=models.Index(fields=['time'], name='main_dublin_time_8fa482_idx'),
        ),
        migrations.AddIndex(
            model_name='dublinweather',
            index=models.Index(fields=['date', 'time'], name='main_dublin_date_f5d8c8_idx'),
        ),
    ]
