# Generated by Django 2.0.6 on 2018-07-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180706_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stops',
            old_name='routes',
            new_name='lines',
        ),
    ]
