# Generated by Django 2.0.6 on 2018-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180619_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublinweather',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
