# Generated by Django 2.0.6 on 2018-07-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180712_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='lineid',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
