# Generated by Django 2.0.6 on 2018-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180619_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublinweather',
            name='dewpt',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dublinweather',
            name='msl',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dublinweather',
            name='rain',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dublinweather',
            name='rhum',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dublinweather',
            name='temp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dublinweather',
            name='vappr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dublinweather',
            name='wetb',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
