# Generated by Django 2.0.6 on 2018-07-30 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_routes_lineid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopid', models.IntegerField(null=True)),
                ('lineid', models.CharField(max_length=10)),
                ('dayofservice', models.CharField(max_length=10)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
            ],
            options={
                'verbose_name_plural': 'Time Table',
            },
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['stopid'], name='main_timeta_stopid_0db765_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['lineid'], name='main_timeta_lineid_6b855b_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['dayofservice'], name='main_timeta_dayofse_481390_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['stopid', 'lineid', 'dayofservice'], name='main_timeta_stopid_d51ede_idx'),
        ),
    ]
