# Generated by Django 2.0.6 on 2018-06-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180619_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=15)),
                ('holiday', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bank Holidays',
            },
        ),
    ]
