# Generated by Django 2.0.6 on 2018-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bankholidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankholidays',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
