# Generated by Django 2.0.5 on 2018-08-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_coefficients_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('stop', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('stage', models.FloatField(null=True)),
                ('pattern_id', models.CharField(max_length=10)),
                ('seq', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Linked Stops',
            },
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['index'], name='main_fares_index_4b19fd_idx'),
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['stop'], name='main_fares_stop_e66422_idx'),
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['route'], name='main_fares_route_bd3630_idx'),
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['direction'], name='main_fares_directi_3f929e_idx'),
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['stage'], name='main_fares_stage_48259a_idx'),
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['pattern_id'], name='main_fares_pattern_01a718_idx'),
        ),
        migrations.AddIndex(
            model_name='fares',
            index=models.Index(fields=['seq'], name='main_fares_seq_3a7c89_idx'),
        ),
    ]
