# Generated by Django 2.0.6 on 2018-06-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180620_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankholidays',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
