# Generated by Django 2.0.6 on 2018-06-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180622_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstopaddress',
            name='stopid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
